# Site settings
title: Alice Windolf
subtitle: "- Traumatherapie - Innere Kindheilung - Coaching"
email: alicewindolf@web.de
description: Du willst endlich Dein Leben selbstbestimmt gestalten? Raus aus Depression, Erschöpfung, Alpträumen, psychosomatischen Beschwerden usw.? Dann bist Du hier richtig. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Alice Windolf
street_address: im Aquariana,<br> Am Tempelhofer Berg 7d
zip_code: 10965
city: Berlin 
state:
country:
phone: 0160 / 7047080

# Social settings
500px_url:
facebook_url: https://www.facebook.com/alice.windolf.9
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/alice-windolf-37734a4b/
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "post"

plugins:
- jekyll-feed
- jekyll-remote-theme

remote_theme: andrewbanchich/editorial-jekyll-theme

