# Site settings
title: Alice Windolf
subtitle: "- Inner Child Healing - Coaching"
email: alicewindolf@web.de
description: Du willst raus aus Überforderung und alten Mustern - dafür rein in Deine Seelenkraft?
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Alice Windolf
street_address: c/o Aquariana, Am Tempelhofer Berg 7Dd
city: Berlin
state:
zip_code: 10965
country:
phone: 0160 / 7047080

# Social settings
500px_url:
facebook_url: https://www.facebook.com/alice.windolf.9
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/alice-windolf-37734a4b/
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "post"

plugins:
- jekyll-feed
- jekyll-remote-theme

remote_theme: andrewbanchich/editorial-jekyll-theme

