# Site settings
title: Alice Windolf
subtitle: "- Burnout-Coaching"
email: alicewindolf@web.de
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Petershagener Straße 15b
city: Briesen/Mark
state:
zip_code: 15518
country:
phone: 0160 / 7047080

# Social settings
500px_url:
facebook_url: https://www.facebook.com/alice.windolf.9
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/alice-windolf-37734a4b/
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "post"

plugins:
- jekyll-feed
- jekyll-remote-theme

remote_theme: andrewbanchich/editorial-jekyll-theme

